# AI Lab-1: Python basics

# Formatted string (f-string & `.format` function)

In [ ]:
# Suppose you have the following variables:
name = "Mufasa"
age = 10

# Let us print them out in 3 ways:
# METHOD 1: Normal
print("My name is", name, "and I am", age, "years old")
# Note how spaces are automatically added between the strings & variables

# METHOD 2: f-string (f stands for "formatted")
print(f"My name is {name} and I am {age} years old")

# METHOD 3: .format function
print(("My name is {} and I am {} years old".format(name, age)))

My name is Mufasa and I am 10 years old
My name is Mufasa and I am 10 years old
My name is Mufasa and I am 10 years old


In [ ]:
# f-string allows for more detailed formatting
n = 314159.2652592
print(f"My number to 3 decimal places = {n:.3f}")
print(f"My number to 3 decimal places in scientific notation = {n:.3e}")
print(f"My number to 3 decimal places printed at a width of 12 = {n:12.3f}")

My number to 3 decimal places = 314159.265
My number to 3 decimal places in scientific notation = 3.142e+05
My number to 3 decimal places printed at a width of 12 =   314159.265


In [ ]:
# .format allows for reordering of the given arguments
a = 42
b = 24
c = 120
print("The 3rd number is {2}, the 1st number is {1}, the 2nd number is {0}".format(a, b, c))
# Note that we must give the index of the argument we want to insert at any point

The 3rd number is 120, the 1st number is 24, the 2nd number is 42


## Lists

In [ ]:
# A list is an ordered set of elements (can be non-homogenous, unlike for array)
L = [1, 2, 'a', 'b']
print(L)

[1, 2, 'a', 'b']


In [ ]:
# Copying a list
copy1 = L
copy2 = L[:]
# If we change copy1, will L change?
copy1[0] = 0
print(f"copy1 = {copy1}, copy2 = {copy2}, L = {L}")
# Yes, but copy2 is unchanged

# If we change copy2, L clearly will not changee
copy2[1] = 100
print(f"copy1 = {copy1}, copy2 = {copy2}, L = {L}")

copy1 = [0, 2, 'a', 'b'], copy2 = [1, 2, 'a', 'b'], L = [0, 2, 'a', 'b']
copy1 = [0, 2, 'a', 'b'], copy2 = [1, 100, 'a', 'b'], L = [0, 2, 'a', 'b']


Hence, we see that assigning the identifier of a list to another identifier simply copies the base address of the list; the list being referenced is still the same. However, when assigning a slice of the list (even if the slice includes the whole list), you are copying only the values and not the base address itself; i.e. this is the way to create a deep copy.

In [ ]:
# "Multi-dimensional" list
L = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
# This is just a list of lists

# By referencing an index of L, you obtain a list that you can reference further
# For example, to reference the 1st element of the 1st list in L
print(L[0][0])
# Here is a weird example for fun
print(L[0:2][1][1])
# Here, we access the 1st 2 lists using the slice, then access the 1st of these 2 lists, then access the index 1 (2nd element) of this list

1
5


**NOTE**: Referencing or slicing an array (ex. a numpy array) is different; here, indices or slices are mentioned within one square bracket only, separeted by commas.

## Linear algebra

Without numpy, write a function computing the matrix multiplication (not element-wise) between `[[1, 2, 3, -8], [4, 5, 6, 7], [-1, -1, 2, 3], [8, 7, 2, 10]]` and `[[-4, 5, 6, -1], [1, 2, 31, 8], [-7, 8, 5, 2], [4, 4, -4, 3]]`.

In [ ]:
L1 = [[1, 2, 3, -8], [4, 5, 6, 7], [-1, -1, 2, 3], [8, 7, 2, 10]]
L2 = [[-4, 5, 6, -1], [1, 2, 31, 8], [-7, 8, 5, 2], [4, 4, -4, 3]]
# Note that you cannot do element-wise multiplication with lists directly
# Out job is somewhat simpler as these represent square matrices

# A function to help pick a particular column (no easy way to do that for lists)
def pickCol(_list, _col):
  max = len(_list) # To help us set the upper bound for iteration
  col = [] # Our would-be column
  for i in range(0, max):
    col.append(_list[i][_col]) # Append the element _col of row i
  return col

final = [[] for i in range(4)] # Making a list of 4 empty row vectors
# NOTE: The final matrix, which will have same number of rows as L1
for i in range(4): # As there are 4 row vectors to deal with for L1
  row = L1[i]
  for j in range(4): # As there are 4 column vectors to deal with for L2
  # We are multiplying each column to the given row, thus getting the corresponding row for the final matrix
    sum = 0
    col = pickCol(L2, j)
    for k in range(4): # As there are 4 elements in each of L1's rows & 4 elements in L2's columns (if they did not match, we could not multiply)
      sum += row[k]*col[k]
    final[i].append(sum)

# Printing the final matrix
print(final)

[[-55, 1, 115, -3], [-25, 106, 181, 69], [1, 21, -39, 6], [1, 110, 235, 82]]


In [ ]:
# Alternate code for the above (more efficient)
final = [[0]*4 for i in range(4)] # Making a matrix of zeros
for i in range (4):
  for j in range(4):
    for k in range(4):
      final[i][j] += L1[i][k]*L2[k][j]

# Printing the final matrix
print(final)

[[-55, 1, 115, -3], [-25, 106, 181, 69], [1, 21, -39, 6], [1, 110, 235, 82]]


**INSIGHTS FROM THE ABOVE CODE**:

1. When operating with the ith row of L1 with the jth column of L2, we get the element at the ith row and jth column in the final matrix
2. A column of a list is obtained by taking the same element index for each row

**EXTRA POINTS**: The number of elements in a row of a list-matrix equals the number of columns in the given list-matrix. The length of a list-matrix equals the number of rows in the list-matrix.

In [ ]:
# NumPy facilitates this whole task
import numpy as np
A1 = np.array(L1)
A2 = np.array(L2)
final = A1.dot(A2)
print(final)

[[-55   1 115  -3]
 [-25 106 181  69]
 [  1  21 -39   6]
 [  1 110 235  82]]
